#!/usr/bin/env bash

# Sauvegarde du fichier /etc/hosts avant de faire des modifications
cp /etc/hosts /etc/hosts.backup

# Modifier localhost pour qu'il résolve vers 127.0.0.2
sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts

# Ajouter une entrée pour facebook.com pour qu'il résolve vers 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts
